'use client'
import React, { useState } from 'react'
import Link from 'next/link'
import { Calendar, CheckCircle, Clock, AlertTriangle, Filter } from 'lucide-react'
import styles from './tasks.module.css'

const TASKS = [
  { id: 't1', title: 'Renew EPC — 14 Mill Lane', property: '14 Mill Lane, Derby', service: 'EPC', due: '2026-06-12', priority: 'Critical', status: 'Pending', cost: 65, autoGenerated: true },
  { id: 't2', title: 'Book Gas Safety — 7 Oak Street', property: '7 Oak Street, Chesterfield', service: 'Gas Safety', due: '2026-06-18', priority: 'Urgent', status: 'Pending', cost: 65, autoGenerated: true },
  { id: 't3', title: 'Book Commercial EPC — Unit 4 Sheffield', property: 'Unit 4, Sheffield', service: 'Commercial EPC', due: '2026-06-15', priority: 'Critical', status: 'Pending', cost: 350, autoGenerated: true },
  { id: 't4', title: 'Book EICR — 22 Victoria Road', property: '22 Victoria Road, Matlock', service: 'EICR', due: '2026-06-30', priority: 'High', status: 'Pending', cost: 150, autoGenerated: true },
  { id: 't5', title: 'Upload Fire Risk Assessment — Unit 4', property: 'Unit 4, Sheffield', service: 'Fire Risk', due: '2026-06-17', priority: 'High', status: 'Pending', cost: 0, autoGenerated: false },
  { id: 't6', title: 'Book EPC renewal — 31 Beech Drive', property: '31 Beech Drive, Nottingham', service: 'EPC', due: '2026-07-05', priority: 'Medium', status: 'Pending', cost: 65, autoGenerated: true },
  { id: 't7', title: 'Book Air Tightness Test — Plot 7', property: 'Plot 7, Meadowbrook', service: 'Air Test', due: '2026-09-01', priority: 'Medium', status: 'In Progress', cost: 200, autoGenerated: false },
  { id: 't8', title: 'Book On-Construction EPC — Plot 7', property: 'Plot 7, Meadowbrook', service: 'On-Construction EPC', due: '2026-09-10', priority: 'Low', status: 'Pending', cost: 75, autoGenerated: true },
]

const PRIORITY_ORDER = ['Critical', 'Urgent', 'High', 'Medium', 'Low']
const PRIORITY_COLORS: Record<string, string> = {
  Critical: '#F87171', Urgent: '#FB923C', High: '#F59E0B', Medium: '#60A5FA', Low: '#4A6280'
}

export default function TasksPage() {
  const [filter, setFilter] = useState('All')
  const [completed, setCompleted] = useState<string[]>([])

  const filtered = TASKS.filter(t => {
    if (filter === 'All') return true
    if (filter === 'Auto') return t.autoGenerated
    return t.priority === filter
  }).sort((a, b) => PRIORITY_ORDER.indexOf(a.priority) - PRIORITY_ORDER.indexOf(b.priority))

  const totalCost = TASKS.reduce((sum, t) => sum + t.cost, 0)
  const pendingCount = TASKS.filter(t => !completed.includes(t.id)).length

  return (
    <div className={styles.page}>
      <div className={styles.pageHeader}>
        <div>
          <h1 className={styles.pageTitle}>Tasks & Timeline</h1>
          <p className={styles.pageSub}>{pendingCount} outstanding actions · £{totalCost} estimated spend</p>
        </div>
      </div>

      {/* Filter Bar */}
      <div className={styles.toolBar}>
        {['All', 'Critical', 'Urgent', 'High', 'Medium', 'Auto'].map(f => (
          <button
            key={f}
            className={`${styles.filterBtn} ${filter === f ? styles.filterActive : ''}`}
            onClick={() => setFilter(f)}
          >
            {f}
          </button>
        ))}
      </div>

      {/* Task List */}
      <div className={styles.taskList}>
        {filtered.map(task => {
          const isDone = completed.includes(task.id)
          const dueDate = new Date(task.due)
          const now = new Date()
          const daysUntil = Math.ceil((dueDate.getTime() - now.getTime()) / 86400000)
          const isOverdue = daysUntil < 0

          return (
            <div key={task.id} className={`${styles.taskCard} ${isDone ? styles.done : ''}`}>
              <button
                className={`${styles.checkBtn} ${isDone ? styles.checked : ''}`}
                onClick={() => setCompleted(prev => isDone ? prev.filter(id => id !== task.id) : [...prev, task.id])}
              >
                {isDone && <CheckCircle size={18} />}
              </button>

              <div className={styles.taskInfo}>
                <p className={styles.taskTitle} style={{ textDecoration: isDone ? 'line-through' : 'none' }}>
                  {task.title}
                </p>
                <p className={styles.taskProp}>{task.property}</p>
                <div className={styles.taskMeta}>
                  <span className={styles.taskService}>{task.service}</span>
                  {task.autoGenerated && <span className={styles.autoTag}>✨ Auto-generated</span>}
                </div>
              </div>

              <div className={styles.taskRight}>
                <div className={styles.taskDue}>
                  <Clock size={12} />
                  <span className={isOverdue ? styles.overdue : daysUntil <= 14 ? styles.urgent : styles.normal}>
                    {isOverdue ? `${Math.abs(daysUntil)}d overdue` : `${daysUntil}d`}
                  </span>
                </div>
                <span className={styles.taskPriority} style={{ 
                  background: `${PRIORITY_COLORS[task.priority]}15`,
                  color: PRIORITY_COLORS[task.priority]
                }}>
                  {task.priority}
                </span>
                {task.cost > 0 && <span className={styles.taskCost}>£{task.cost}</span>}
                {!isDone && (
                  <Link
                    href={`/book?service=${encodeURIComponent(task.service)}&property=${encodeURIComponent(task.property)}`}
                    className={styles.bookBtn}
                  >
                    Book
                  </Link>
                )}
              </div>
            </div>
          )
        })}
      </div>
    </div>
  )
}
